### ISSUE TITLE
make: Nothing to be done for 'start'.

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/pre-processing#14]
https://github.com/remindmodel/pre-processing/blob/641fb71df04f64c459a77445e5ef6051aa2329f5/Makefile#L1

**Comment by pascal-sauer** [comment]
https://github.com/remindmodel/pre-processing/commit/90e8c6cf4ba54077e323cc713986c8bf3344f34c
